<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-FAJDTI3" name="interviewquestion.Exceptionhandling$SetTimeoutTestCase" tests="1" failures="0" timestamp="2020-05-10T19:28:36 IST" time="2.036" errors="1">
  <testcase name="timeout" time="2.036" classname="interviewquestion.Exceptionhandling$SetTimeoutTestCase">
    <error type="org.testng.TestException" message="
Expected exception of type class java.lang.NullPointerException but got org.testng.internal.thread.ThreadTimeoutException: Method interviewquestion.Exceptionhandling$SetTimeoutTestCase.timeout() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.NullPointerException but got org.testng.internal.thread.ThreadTimeoutException: Method interviewquestion.Exceptionhandling$SetTimeoutTestCase.timeout() didn't finish within the time-out 2000
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:719)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:616)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method interviewquestion.Exceptionhandling$SetTimeoutTestCase.timeout() didn't finish within the time-out 2000
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:366)
at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- timeout -->
</testsuite> <!-- interviewquestion.Exceptionhandling$SetTimeoutTestCase -->
